[options]
addons_path =
    odoo/addons,
    modulos/modulos-terceros,
    modulos/oca/account-financial-reporting,
    modulos/oca/account-financial-tools,
    modulos/oca/account-fiscal-rule,
    modulos/oca/account-invoice-reporting,
    modulos/oca/account-invoicing,
    modulos/oca/account-payment,
    modulos/oca/account-reconcile,
    modulos/oca/bank-payment,
    modulos/oca/bank-statement-import,
    modulos/oca/brand,
    modulos/oca/calendar,
    modulos/oca/community-data-files,
    modulos/oca/connector,
    modulos/oca/contract,
    modulos/oca/credit-control,
    modulos/oca/delivery-carrier,
    modulos/oca/dms,
    modulos/oca/e-commerce,
    modulos/oca/edi,
    modulos/oca/event,
    modulos/oca/field-service,
    modulos/oca/fleet,
    modulos/oca/helpdesk,
    modulos/oca/hr,
    modulos/oca/hr-attendance,
    modulos/oca/hr-holidays,
    modulos/oca/knowledge,
    modulos/oca/l10n-spain,
    modulos/oca/manufacture,
    modulos/oca/manufacture-reporting,
    modulos/oca/mis-builder,
    modulos/oca/partner-contact,
    modulos/oca/payroll,
    modulos/oca/pos,
    modulos/oca/product-attribute,
    modulos/oca/product-pack,
    modulos/oca/product-variant,
    modulos/oca/project,
    modulos/oca/queue,
    modulos/oca/reporting-engine,
    modulos/oca/sale-reporting,
    modulos/oca/sale-workflow,
    modulos/oca/server-auth,
    modulos/oca/server-brand,
    modulos/oca/server-env,
    modulos/oca/server-tools,
    modulos/oca/server-ux,
    modulos/oca/social,
    modulos/oca/stock-logistics-reporting,
    modulos/oca/stock-logistics-warehouse,
    modulos/oca/storage,
    modulos/oca/timesheet,
    modulos/oca/web,
    modulos/oca/web-api,
    modulos/oca/website
admin_passwd = 2552
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = db
db_maxconn = 64
db_name = odoo
db_password = odoo
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter =
demo = {}
email_from = False
from_filter = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface = 0.0.0.0
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 3600
limit_time_real = 7200
limit_time_real_cron = -1
list_db = False
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile =
longpolling_port = 8072
max_cron_threads = 2
proxy_mode = True
reportgz = False
server_wide_modules = base,web
syslog = False
test_enable = False
unaccent = False
workers = 2
without_demo = True
